easy_admin:
   entities:
       # List the entity class name you want to manage
      #  - App\Entity\Product
      #  - App\Entity\Category
       - App\Entity\PageAlex
       - App\Entity\PageMelvin
       - App\Entity\PageLudi
       - App\Entity\User
       - App\Entity\Article
